name: Client CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true

    - name: Install
      run: |
        set -o pipefail
        npm ci
        cd client
        npm install

    - name: lint
      run: |
        npm run lint

    - name: build
      run: |
        npm run build

    - name: test
      run: |
        npm test
